---
title: "Developement notes"
author: "Nathan Brouwer"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

## PROJECT: Replicating and extending Full annual cycle (FAC) model of Runge and Marra in Birds of Two Worlds

Project Initiated: Spring 2016
This README consolidated: Thu Jun 30 10:38:45 2016
Results present at NAOC meeting, Aug 2016
Project Re-initiated: Oct 2017


## /R Files

### Equations

* Functions that implement a specific equation are name eqX where X is the function name.  
* It would be nice to alias them to something that says what the function does.



## ORIGINAL FILES ASSOCIATED WITH PROJECT

## README

this file; readme and misc notes from project development

## 1FAC_subfnxns.R

separate functions for each equation in Runge & Marra model


Functions to implement Runge and Mara Birds of Two Worlds FAC model "Chapter 28: Modeling seasonal interactions in the population dynamics of migratory birds"

Each equation in the paper typically has a separate function associated with it There are also functions to do other tasks such as make a dataframe to hold the output of the model

These functions are called by S2_runge_MAIN_FNXN [this file name outdated] to implement a single run of the model


## 2FAC_runFAC.R

(previously: S2_runge_MAIN_FNXN.R)

Main function to implement the model; call equations from 1FAC_subfnxns

Function to implement Runge and Mara Birds of Two Worlds FAC model This function iterates the models for a specificed number of times (reps = ...) in order todetermine the equilibrium population densities It calls on subfunctions in 1FACE_subfnxns.R 

It is *called* by Sx3_rung_FAC_FXN_apply_model... [file name outdated]




## 3FAC_rungMultiFAC.R

Previously:
S3_runge_FXN_apply_model_accross_range_of_values: 

calls S_runFAC.R recurcively accross a range of conditions, such as different parameter values or population sizes



##
S4_runge_run_mods:  
script to run the models; calls

##
S3_runge_FXN_apply_model_accross_range_of_values

##
S5_runge_MAIN_FNXN_refac: 
my refactoring of certain functions to avoid compliated conditional statements in R&M's original model

##
S6_runge_testing_code:
code to test the model to see why I can't reproduce their figures


## Original Runge & Marra implementation

Runge & Marra ran 3 simulations
1. change relative amounts of breeding and wintering habitat
2. vary intensity of sexual habitat segregation (gamma)

3. vary intensity of winter to summer carry over (c)
"We assumed what winter survival rates did not differ by sex or habitat (Marra and Holmes 2001)" pg 381 col 1

Table 28.1
Table 28.1

"capacity of the sink breeding habitat was set at a level (10,000) much higher than the other carrying capacities, so that it was effectivley unlimited" pg 382 col 1 

"During the breeding season, we assumed that survival did not differ by  sex, but did depend on habitat" pg 381; Table 28.2




 SUMMER DYNAMICS

Summer dynamics involved allocating male and female individuals that originated from different qualities of winter habitat to different qualities of summer habitat When I built my model, I had a laborious algorithm doing the  accounting for this allocation, working through each part of theallocation step by step. Their algorithm appears to be more elegant


FECUNDITIES 
pg 381 col 2.  
Table 28.3
"We simplified the eight fecundity rates into three parametrers: a base rate, a habitat effect, and a carry-over effect [c]. Note that these fecundity rates are the nubmer of young per pair that are alive ad the end of the breeding season; thus, they incorporate all components of fecundity, including fledgling survival"
 "To simplify the carry-over effect of winter habitat on subsequent  productivity, we assumed that for each member of a pair that spent the previous  winter in poor habitat, the fecundity of the pair was reduced by a factor of c.S




WINTER SITE COMPETITION
 pg 381, table 28.4.
"We simplified the nine competitive factors into three effects: 
 the competitive ability for good winter habitat of birds
 that bred in or fledged from source habitat 
 the relative competitive ability of young compared w/ adults;
 the relative ability of males compared w/ femaels
 Birds from sinke habitat were assumed to have 1/10th the comp ability of birds from 
 source habitat, owing possibly to a later arrival data
 LIkewise, young were assumed to have 1/5th the comp 
 ability of adults.
 To explore the effect of maile-biased comp for good witner
 habitat, we defined a mle dom parametr, gamma
 that we allowed to vary from 1 (equal comp ability between
