---
title: "Misc notes"
author: "Vignette Author"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```



## Preceding models

### Carry-over effect

eg spring to fall

* Pulliam 1987?

### FAC

* Fretwell 1972
  - Graphical?
  - Analytical
* Sherry & Holmes 1972
  - Graphical


Lebreton & CLobert 1991?

Density dependence occurs when the rate at which an ecological process occurs
Density dependence plays a central role in population ecology, community ecology, and evolutionary biology
While there are a multitude of theoretical models which incorporate dd few of these are demographic-explicit models which incoporate key factors such as ....
Density dependnet matrix, integral proejction, individual-based, and integrated popualtion but they are the exception rather than the rule.

Bird p




Pulliam

"ecologists often study population growth and regulation with little or no attention paid to the differences in birth and death rates that occur in different habitats"

Pulliam is not the 1st to talk about source/sinks or the 1st to model it
"Several authors (Lidicker 1975; Van Horne 1983) have discussed the need to distinguish between source and sink habitats in field studies of population regula- tion; however, most theoretical treatments (Gadgil 1971; Levin 1976; McMurtie 1978; Vance 1984) of the dynamics of single-species populations in spatially subdivided habitats have not explicitly addressed the maintenance of populations in habitats where reproduction fails to keep pace with local mortality. Holt (1985) considered the dynamics of a food-limited predator that occupied both a source habitat containing prey and a sink habitat with no prey. He demonstrated that passive dispersal from the source can maintain a population in the sink and that the joint sink and source populations can exceed what could be maintained in the source alone."
