---
title: "w) Annotated bibliography"
author: "Nathan L. Brouwer"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{w) Annotated bibliography}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
editor_options: 
  chunk_output_type: console
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```



Paxton et al 2017.  Journal of Avian Biology.  Survivorship across the annual cycle of a migratory passerine, the willow flycatcher.
https://onlinelibrary.wiley.com/doi/abs/10.1111/jav.01371

Abstract
Annual survivorship in migratory birds is a product of survival across the different periods of the annual cycle (i.e. breeding, wintering, and migration), and may vary substantially among these periods. Determining which periods have the highest mortality, and thus are potentially limiting a population, is important especially for species of conservation concern. To estimate survival probabilities of the willow flycatcher Empidonax traillii in each of the different periods, we combined demographic data from a 10‐year breeding season study with that from a 5‐year wintering grounds study. Estimates of annual apparent survival for breeding and wintering periods were nearly identical (65–66%), as were estimates of monthly apparent survival for both breeding and wintering stationary periods (98–99%). Because flycatchers spend at least half the year on the wintering grounds, overall apparent survivorship was lower (88%) on the wintering grounds than on the breeding grounds (97%). The migratory period had the highest mortality rate, accounting for 62% of the estimated annual mortality even though it comprises only one quarter or less of the annual cycle. The migratory period in the willow flycatcher and many other neotropical migrants is poorly understood, and further research is needed to identify sources of mortality during this crucial period.


Saino et al.  2016.  Sex‐dependent carry‐over effects on timing of reproduction and fecundity of a migratory bird.  Journal of Animal Ecology. 
https://besjournals.onlinelibrary.wiley.com/doi/abs/10.1111/1365-2656.12625

Abstract
Life of many organisms flows as a sequence of annual cycles. Timing of cyclical events is shaped by natural selection also via the domino effects that any life history stage has on the stages that follow. Such ‘carry‐over effects’ have major consequences for evolutionary, ecological and demographic processes, but the causes that generate their individual‐level variation, including the effect of sex, are poorly understood.
We used light‐level geolocators to study carry‐over effects on the year‐round life cycle of the long‐distance migratory barn swallow (Hirundo rustica) and sex‐dependent variation in their strength.
Correlation analyses showed that timing of breeding influenced departure time for autumn migration in females but not in males. In addition, strong, time‐mediated carry‐over effects of timing of departure from the wintering areas in sub‐Saharan Africa for spring migration on timing of arrival to the breeding grounds in Italy and Switzerland operated in both sexes. However, carry‐over effects of spring migration phenology on breeding date and seasonal fecundity were observed among females but not among males.
We used partial least squares path modelling to unveil the complex carry‐over effects of phenology during the non‐breeding season in combination with the ecological conditions experienced by individual swallows in the wintering area, as gauged by Normalized Difference Vegetation Index values (NDVI), on breeding performance. Phenology during the non‐breeding season combined with NDVI during wintering accounted for as much as 65–70% of variation in subsequent seasonal fecundity in females, while such carry‐over effects on breeding success of males were weaker.
Intense, sex‐specific carry‐over effects can have impacted on evolutionary processes, including sexual selection, and affected phenological response to climate change, causing the large population decline observed in this species.




Peele 2015.  Population regulation of a migratory songbird in the non-breeding season: A test of buffer and crowding effects.  Dissertation.
https://search.proquest.com/openview/afa435cdcbb66666b151bc84b35a781a/1?pq-origsite=gscholar&cbl=18750&diss=y


## Preceding models

### Carry-over effect

eg spring to fall

* Pulliam 1987?

### FAC

* Fretwell 1972
  - Graphical?
  - Analytical
* Sherry & Holmes 1972
  - Graphical


Lebreton & CLobert 1991?

Density dependence occurs when the rate at which an ecological process occurs
Density dependence plays a central role in population ecology, community ecology, and evolutionary biology
While there are a multitude of theoretical models which incorporate dd few of these are demographic-explicit models which incoporate key factors such as ....
Density dependnet matrix, integral proejction, individual-based, and integrated popualtion but they are the exception rather than the rule.

Bird p




Pulliam

"ecologists often study population growth and regulation with little or no attention paid to the differences in birth and death rates that occur in different habitats"

Pulliam is not the 1st to talk about source/sinks or the 1st to model it
"Several authors (Lidicker 1975; Van Horne 1983) have discussed the need to distinguish between source and sink habitats in field studies of population regula- tion; however, most theoretical treatments (Gadgil 1971; Levin 1976; McMurtie 1978; Vance 1984) of the dynamics of single-species populations in spatially subdivided habitats have not explicitly addressed the maintenance of populations in habitats where reproduction fails to keep pace with local mortality. Holt (1985) considered the dynamics of a food-limited predator that occupied both a source habitat containing prey and a sink habitat with no prey. He demonstrated that passive dispersal from the source can maintain a population in the sink and that the joint sink and source populations can exceed what could be maintained in the source alone."




## Sherry & Holmes 1995


The cannonical model of population dynamics in migratory landbirds was present by Sherry and Holmes (1995)
"Summer versus winter limitation of populations: what are the issues and what is the evidence?, p. 85–120. Ecology and management of Neotropical migratory"

"We envision the life cycle of Neotropical-Neartic migrant birds as compsied, in simplest terms. of two major aseson of selecting a habitat and either breeding (Summer) or surviving (summar and winter).  Between these two seasons is a migration period that also can invovle selection of habitat and certainly mortality..." (pg 87)  

"Neotropical-Neacrtic migrant birds often occupy mulitpole habitats and disperse widely....compared to most other organisms, suggesting that population dynamics must be examined at multiple-habitat or greater spatial scales, a relatively neglected toic in many past studies of population regulation.  Models of how animals use habitats assume that, at times of low population density individual will occupy those habitats in which they can acheive greatest fitness, referred to here as the primary habitats.  Fretweel and Lucal (1970; Frewell 1972) and brouwer (1969b) devised explicity graphical models for the declin in fitness...as the density of animals increases in the primary habitat.  Furthermore, they noted that continued increase in density willo depress suitability of primary habitat to the level acheived by individuals settling in a secondary habitat, at which point they should settle in both habitats.  Increasing density shoudl cause further suitablity declines in both habitats as animals continue to settle both areas.  At some point, further increases in density cause suitability to decline to such a level that individula scannot reproduce or even maintina themselves, at which point they become 'floaters,' searching for unoccupied patches or newly created habitat vacancies.... Fretwell and Lucas also distinquish two habitat-settlement mechanisms with correspondingly different patterns of density dependent distributions of abundances and suitabilites among the habitats.  IN the 'ideal-free' case, individuals settle independnetly (Free) of each other in the optimum habitat, such that at any given density fitnesses and suitabilities are equalitzed among all occupeid habitats.  In the 'ideal despotic' case, individuals settling first in preferred habitats constrain the settlement of subsequence individuals, e.g. via territorial behavior, such that fitness of individuals in secondary habitats is less that that of individuals in primary habitats." (pg 89)
Further research
Rosenzweig, Morris, Puliam, Bernstein

"density-dependent habitat use...leads to potentially powerful regulatory mechanisms, which could operate widely in Neotropical-Nearctic mgirant birds.  Specifically, despotic habitat selection could stabilize population dynamcis in multiple-habitat landscapes, both via increased dispersal at grater poulation densities and via declining per capitat fitness as a population in constrained at greater densities to occupy increasinly less suitable habitat"
Lomnicki, O'Connor, NEwton, ANdre, Dhodnt

"Dhondt et al (1992) for example showed that clutch size in European tits decliens with density not b/c average clutch size declines within good habitat, but because small clutches are produced in secondary habitats.  This idea of reduced average per captiat fitness at higher densities ...leads to an asumptotic relatiosnhip between the total number of young produces (or survival, depending on season) and population density.  In other words, above some desnity at which suitable habitats become saturated, either no more young will be produced and/or adult [average?] survival will decline -- a crucial relationship for understanding the joint influence of summar and winter habitats on population size...." (pg 89)

"This mechanism of density-dependnet fitness variation may be widspread in Neotropic-Neacrtic migrants if despotic habitat-use patterns cause fitness to decline in secondary habitats.  Some evidence suggests that fitness does depend on habiatt, often in (89) relation to bird age in migrant species ....  Such a mechanism could operate both in the breeding season and during witner, particularly if birds compete for limited amoutns of the highest quality habitats."  There is strong evdience of the and they "emphasize the possiblity that such density dependent habitat selection may have a major impact on population dynamics" (90)

"Most explicity theoretical discussion of seasonal populations model: (1) population size in autumn as a functio f that in spring (Basedon on summer habitat-selection processes, related primarily to nest site choice and reproduction); (2) spring population size as a functio of that in autumn (taking into consdieration witner habiat-selection processes, related to winter survival); and (3) combine thse two sets of events mathematically or graphically.  We fllow PUlliam's (1987) treatment here...to dedeuce the possible shapes of the curve of autumn poulation size as a function of that in spring.  His ideal-domiance curve...seems most appropriate for N/N migrants, based on their widespread territoriality and intraspectific compeititon for preferred breeding and witnering sites...A similar ideal-domiance curve is probably most appropriate for spring populations asa fucntio nof those in teh fall...The 'ideal' part of the model assumes both that birds can disperse widely among an array of habiatats and can assess their quality.." (pg 91)

* Fretwell 1972
* PUlliam 1987 (1988?).  Sources, sinks, and poulation regulation.  Am. Nat 132.  652-661.
* LeBreton and Clobert 1991.  Bird population dynamics, management, and conservation: the role of mathematical modelling.  in Bird population studies: relevance to conservation and management.

