#' Make combinations of parameters for parameter matrix
#'
#' This takes a df of parameter ranges generated by paramRanges.df()
#' and applied makeParamSeq() to turn any that vary into a sequence spanning
#' the range.
#' These sequences (if any) are then turned into a matrix of all possible values
#' if none vary, then a single row of data is returned
#'
#' Formerly aliased as makeParamCombos.df
#'
#' @param paramRanges Input range (min, max) for each paramters
#' @param var.length Step size (?)
#'
#' @return ParamCombos.df Dataframe of parameter combinations
#'
#' @export

makeParCombos <- function(paramRanges = makeParamRanges.df(),
                               var.length = 10){

  paramRanges["K.bc","min"] <- ifelse(paramRanges["K.bc","min"] == 0, 1,  #Change zeros to 1 to make model avoid errors
                                      paramRanges["K.bc","min"])
  paramRanges["K.bk","min"] <- ifelse(paramRanges["K.bc","min"] == 0, 1,
                                      paramRanges["K.bk","min"])
  paramRanges["K.wg","min"] <- ifelse(paramRanges["K.bc","min"] == 0, 1,
                                      paramRanges["K.wg","min"])



  for(i in 1:dim(paramRanges)[1]){                          #Assign min and max ranges
    i.range <- c(paramRanges[i,"min"],paramRanges[i,"max"])


    if(is.na(i.range[1]) == TRUE){next}   #Skip over any meta data included in parameter info

    #if(is.na(i.range[1]) == TRUE){next}

    #Set range of gamma values
    i.seq <- makeParamSeq(i.range,
                          var.length)
    i.name <- paste(row.names(paramRanges)[i],"Seq",sep = "")
    assign(i.name, value = i.seq)
  }

  ParamCombos.df <- expand.grid(
    gamma  = gammaSeq
    ,co      = coSeq
    ,K.bc   = K.bcSeq
    ,K.bk   = K.bkSeq
    ,K.wg   = K.wgSeq

    #sex ratio at birth
    ,f = fSeq

    #Winter SURVIVAL (S.w)
    ,S.w.mg = S.w.mgSeq
    ,S.w.mp = S.w.mpSeq
    ,S.w.fg = S.w.fgSeq
    ,S.w.fp = S.w.fpSeq

    #Spring (Northward) migration SURVIVAL (S.m)
    ,S.m.mg = S.m.mgSeq  #do they call this s.smg?
    ,S.m.mp = S.m.mpSeq
    ,S.m.fg = S.m.fgSeq
    ,S.m.fp = S.m.fpSeq

    #FECUNDITIES
    ,R.base.rate = R.base.rateSeq
    ,R.hab.effect = R.hab.effectSeq   #effects of pair breeding in poor habitat



    #Breeding season mortality
    ,S.b.mc = S.b.mcSeq #males in sour.c.e habitat
    ,S.b.mk = S.b.mkSeq #males in sin.k. habitat
    ,S.b.md = S.b.mdSeq #"drain" males
    ,S.b.fc = S.b.fcSeq
    ,S.b.fk = S.b.fkSeq

    #FALL (southward) MIGRATION Mortality of ADULTS
    #pg 381; Table 28.2
    ,S.f.mc = S.f.mcSeq #males from sour.c.e
    ,S.f.mk = S.f.mkSeq
    ,S.f.md = S.f.mdSeq #drain males have higher surv b/c they don't have costs of repro
    ,S.f.fc = S.f.fcSeq
    ,S.f.fk = S.f.fkSeq

    #FALL MIGRATION Survival of OFFSPRING
    ,S.y.mc = S.y.mcSeq
    ,S.y.mk = S.y.mkSeq
    ,S.y.fc = S.y.fcSeq
    ,S.y.fk = S.y.fkSeq)

  #Clean up
  rm(list = paste(row.names(na.omit(paramRanges)),"Seq",sep = "")) #na.omit() used to exclude any metadata

  #Diagnostic
  cat("The dimension of the dataframe is", dim(paramRanges))

  return(ParamCombos.df)
}
